### ISSUE TITLE
Failed to retrieve project containers

### ISSUE THREAD

**Issue by laurencefass** [p1c2u/vscode-docker-compose#15]
when i click refresh there is no console activity (i.e. errors) and no network activity.

i have a valid docker-compose.yml file in the project.

```
version: '2.1'

services:
  docker-example:
    image: docker-example
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
```
